### ISSUE TITLE
[FEATURE]: Show registration success

### ISSUE THREAD

**Issue by jonahgoldwastaken** [theonejonahgold/wat-zegt-deze-brief#59]
## Job story

Whenever I have created my account, I want to see if the registration has succeeded or not, so I can start using the app with my account.

## Tasks

- [x] Front-end: SvelteKit goto success page on successful registration
- [x] Front-end: Style success page properly
- [x] Front-end: Provide clear call-to-action to verify e-mail
- [x] Front-end: Diversify success messages based on user role
