### ISSUE TITLE
[FEATURE]: Login user with confirmation e-mail

### ISSUE THREAD

**Issue by jonahgoldwastaken** [theonejonahgold/wat-zegt-deze-brief#65]
## Job story

Whenever I confirm my e-mail address, I want to be logged in immediately, so I can start using the app right away

## Tasks

- [x] Converge back-end into front-end
- [x] Save session as cookie
- [x] Redirect to dashboard when registration is complete
