### ISSUE TITLE
[IMPROVEMENT]: Replace all png's with svg's

### ISSUE THREAD

**Issue by victorboucher** [theonejonahgold/wat-zegt-deze-brief#93]
## Describe the improvement?
Replace all the images in /static/images with svg's (in the assets/icon directory)

## What does it improve?
Image quality and freedom of scale. Better load times etc.

## Where does the improvement take place?
At a lot of different places

## Tasks

- [ ] Export all needed images as SVG's from the XD file
- [ ] Place them into the icons/assets directory
- [ ] Import them everywhere they are needed
- [ ] Add styling to make sure everything looks good
